### ISSUE TITLE
Trunk fails to build on OSX 10.7

### ISSUE THREAD

**Issue by GoogleCodeExporter** [steve-o/openpgm#11]
```
Using revision 1458 from trunk, libpgm fails to compile. The build log states:

sockaddr.c: In function 'pgm_sockaddr_pktinfo':
sockaddr.c:485: error: 'IPV6_PKTINFO' undeclared (first use in this function)
sockaddr.c:485: error: (Each undeclared identifier is reported only once
sockaddr.c:485: error: for each function it appears in.)
make: *** [libpgm_noinst_la-sockaddr.lo] Error 1

A solution from MacPorts is to add the following to includes/config.h:

#define __APPLE_USE_RFC_2292

```

Original issue reported on code.google.com by `ScottALyons` on 12 Dec 2011 at 12:15
